version: '3'
services:
  database:
    image: postgres:11-bullseye
    shm_size: '1024m'
    ports:
      - "5409:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - meldr_network
  app:
    build: ./app
    ports:
      - "80:8000"
    links:
      - database
    env_file:
      - .env
    volumes:
      - ./app:/app
    networks:
      - meldr_network

volumes:
  postgres-data:

networks:
  meldr_network:
    external: true
